### ISSUE TITLE
Where's the `ddddddd` commit?

### ISSUE THREAD

**Issue by bl-ue** [orsenkucher/orsenkucher#1]
@orsenkucher where's the `ddddddd` commit you mention in your bio?
>I have commit with `ddddddd` hash😎

**Comment by orsenkucher** [comment]
@bl-ue yo, found it 
https://github.com/orsenkucher/hydrated_bloc/commit/ddddddd96f130f7d6d44a880eeff983b68016197
For sure it's impossible to have the full hash with `d`'s, but enough for the short form, haha

**Comment by bl-ue** [comment]
Wow, that's so cool!  I've never seen anything like that.  Thank you for finding it for me! 😄

**Comment by bl-ue** [comment]
Oh it's also here: https://github.com/felangel/hydrated_bloc/commit/ddddddd96f130f7d6d44a880eeff983b68016197

**Comment by bl-ue** [comment]
I think that's a good thing to be able to display on your bio! 😆
